- hosts: all
  become: true
  roles:
    - role: ansible-role-conjur
      conjur_account: conjur
      conjur_appliance_url: 'https://conjur-master-v2.itp.conjur.net/api'
      conjur_host_factory_token: "{{lookup('env', 'HFTOKEN')}}"
      conjur_ssl_certificate: "{{lookup('file', '~/conjur-conjur.pem')}}"
      conjur_host_name: 'test1234567890'
      conjur_validate_certs: no
      conjur_ssh_enable: yes
