- name: Create group conjur
  group:
    name: conjur
    state: present

- name: Place Conjur public SSL certificate
  copy:
    dest: /etc/conjur.pem
    content: "{{conjur_ssl_certificate}}"
    mode: 0644

- name: Symlink Conjur public SSL certificate into /etc/ssl/certs
  file:
    src: /etc/conjur.pem
    dest: /etc/ssl/certs/conjur.crt
    state: link
  register: cert_symlink

- name: Rehash certs
  command: 'c_rehash'
  when: cert_symlink.changed

- name: Render /etc/conjur.conf
  template:
    src: templates/conjur.conf.j2
    dest: /etc/conjur.conf
    mode: 0644

- block:
  - name: Request identity from Conjur
    uri:
      url: "{{conjur_appliance_url}}/host_factories/hosts"
      method: POST
      body: "id={{conjur_host_name}}"
      headers:
        Authorization: Token token="{{conjur_host_factory_token}}"
        Content-Type: "application/x-www-form-urlencoded"
      status_code: 201
      validate_certs: "{{conjur_validate_certs}}"  # using a self-signed cert is coming in Ansible 2.3 - https://github.com/ansible/ansible/pull/18141
    register: host_factory_response

  - name: Place identity file /etc/conjur.identity
    template:
      src: templates/conjur.identity.j2
      dest: /etc/conjur.identity
      mode: 0640
      group: conjur
  when: not conjurized
