version: '2'
services:
  postgres:
    image: postgres:9.3
    container_name: ansible-postgres

  conjur:
    image: cyberark/conjur:0.1.0-stable
    container_name: ansible-conjur
    command: server -a cucumber
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      DATABASE_URL: postgres://postgres@postgres/postgres
      CONJUR_DATA_KEY: "W0BuL8iTr/7QvtjIluJbrb5LDAnmXzmcpxkqihO3dXA="
      PORT: 3000
    depends_on:
      - postgres

  client:
    image: conjurinc/cli5
    container_name: ansible-conjur-client
    entrypoint: sleep
    command: infinity
    volumes:
      - ./:/conjurinc/ansible/
    environment:
      CONJUR_APPLIANCE_URL: http://conjur:3000
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: admin
    depends_on:
      - conjur

  target:
    build:
      context: .
      dockerfile: Dockerfile.target
    container_name: ansible-target
    entrypoint: sleep
    command: infinity
